package kr.co.groovy.enums.hold;

public enum NotificationKind {
    DUTY_REQUEST, ANSWER, TEAM_NOTICE, COMPANY_NOTICE, SCHEDULE, NEW_CHATTING_ROOM, EMAIL_RECEPTION, ELECTRON_SANCTION_RECEPTION, ELECTRON_SANCTION_RESULT

    }
